spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/todo
    username: todo
    password: todo
  # jpa properties
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
