spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${TODO_DATASOURCE}}:5432/todo
    username: ${TODO_USER}
    password: ${TODO_PASSWORD}
  # jpa properties
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
